# Generated by Django 6.1 on 2026-08-21 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proyecto',
            new_name='Project',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='duracion',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='nombre',
            new_name='name',
        ),
    ]
