# Generated by Django 6.1 on 2026-09-17 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0003_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='projects/logo.png', upload_to='projects'),
        ),
    ]
